// mfe-react/src/pages/Home.tsx
import { eventBus } from '@mfe/shared'

export function Home() {

  const handleLogin = () => {
    console.log('Button Clicked');
    
    eventBus.emit('user:login', { userId: '1', role: 'admin' })
  }

  return (
    <div>
      <h1>React Micro-app</h1>
      <p>This app is served by mfe-react on port 3001.</p>
      <button onClick={handleLogin}>Emit login event</button>
    </div>
  )
}

// mfe-vue/src/pages/Home.vue
<template>
  <div>
    <h1>Vue Micro-app</h1>
    <p>This app is served by mfe-vue on port 3002.</p>
    <button @click="emitLogin">Emit login event</button>
  </div>
</template>

<script setup lang="ts">
import { eventBus } from '@mfe/shared'

function emitLogin() {
  eventBus.emit('user:login', { userId: '2', role: 'user' })
}
</script>
